resume: false
finetune: true
test_only: false
num_workers: 1

required_devices: 1
no_test: false
debug: false
log2tb: true
allow_double_bs: false
seed: 0
distributed: false
test_freq: 1
print_freq: 100

dataset:
  name: "glove"
  full_res: true
  batch_size: 32
  video_clip_duration: 0.5
  video_fps: 16.
  transforms: "msc+color"
  crop_size: 224
  audio_clip_duration: 2.
  audio_fps: 24000.
  spectrogram_fps: 100.
  n_fft: 512
  train:
    split: "all_train"
    use_augmentation: true
    drop_last: true
    clips_per_video: 1
  test:
    split: "all_val"
    use_augmentation: false
    drop_last: true

optimizer:
  name: "adam"
  weight_decay: 0.00001
  num_epochs: 55
  lr:
    name: "multistep"
    base_lr: 0.0005
    gamma: 1.
    milestones: [10, 20, 30, 40, 45, 55]

model:
  name: "Cross-N1024-ft-ssl"
  model_dir: "checkpoints/AVID/Glove"
  arch: "av_wrapper"
  args:
    proj_dim: [512, 512, 128]
    video_backbone: "R2Plus1D"
    video_backbone_args:
      depth: 18
    audio_backbone: "Conv2D"
    audio_backbone_args:
      depth: 10

loss:
  name: "AVID"
  args:
    num_data: 545
    # num_data: 2725
    # num_data: 1784108
    num_negatives: 16
    momentum: 0.5
    xModal_coeff: 1.
    wModal_coeff: 0.